"use client";

import React, { useState } from "react";
import { useResearchStore } from "@/store/useResearchStore";
import { useI18n } from "@/lib/i18n";
import { SurveyQuestionnaireResult } from "@/lib/ai/gemini";
import { AcademicTooltip } from "@/components/ui/AcademicTooltip";
import {
  Sparkles,
  FileText,
  Copy,
  Check,
  Printer,
  Download,
  ShieldCheck,
  AlertCircle,
  HelpCircle,
  Loader2,
  Users,
  Settings2,
  ListOrdered,
  Layers,
  ChevronRight,
  BookOpen
} from "lucide-react";

export function SurveyArchitect() {
  const { userProfile, locale } = useResearchStore();
  const { t } = useI18n(locale);

  // Form State
  const [topic, setTopic] = useState<string>(
    userProfile.primaryInterest || "Adoption and Impact of AI-Assisted Programming Tools among University Students"
  );
  const [variables, setVariables] = useState<string>(
    "Perceived Coding Efficiency, Conceptual Understanding, Academic Integrity Concerns"
  );
  const [methodologyType, setMethodologyType] = useState<"quantitative" | "qualitative">("quantitative");
  const [targetAudience, setTargetAudience] = useState<string>(
    "Undergraduate Computer Science & Engineering Students"
  );
  const [isLoading, setIsLoading] = useState<boolean>(false);
  const [copied, setCopied] = useState<boolean>(false);
  const [surveyData, setSurveyData] = useState<SurveyQuestionnaireResult | null>(null);

  // Presets for quick student testing
  const presets = [
    {
      label: locale === "bn" ? "এআই কোডিং টুলস (CSE)" : "AI Coding Tools (CSE)",
      topic: "Adoption and Impact of AI-Assisted Programming Tools among University Students",
      vars: "Perceived Coding Efficiency, Conceptual Understanding, Academic Integrity",
      aud: "Undergraduate Computer Science Students",
      type: "quantitative" as const
    },
    {
      label: locale === "bn" ? "ডিজিটাল ফাইন্যান্স (BBA)" : "Fintech / Mobile Banking (BBA)",
      topic: "User Trust and Financial Inclusion in Mobile Financial Services in Bangladesh",
      vars: "System Usability, Transaction Security, Behavioral Adoption Intent",
      aud: "Rural Micro-merchants and Retail Consumers",
      type: "quantitative" as const
    },
    {
      label: locale === "bn" ? "টেলিমেডিসিন অভিজ্ঞতা (স্বাস্থ্যবিজ্ঞান)" : "Telemedicine Experience (Health)",
      topic: "Lived Experiences and Clinical Barriers of Remote Patient Monitoring",
      vars: "Doctor-Patient Rapport, Diagnostic Confidence, Technical Friction",
      aud: "Registered Medical Practitioners and Rural Patients",
      type: "qualitative" as const
    },
    {
      label: locale === "bn" ? "শ্রম আইন ও অধিকার (আইন/সমাজবিজ্ঞান)" : "Labor Rights & Compliance (Law)",
      topic: "Implementation of Occupational Safety and Legal Redress in Manufacturing Hubs",
      vars: "Institutional Enforcement, Grievance Transparency, Worker Awareness",
      aud: "Garment Industry Workers and Labor Union Representatives",
      type: "qualitative" as const
    }
  ];

  const applyPreset = (p: typeof presets[0]) => {
    setTopic(p.topic);
    setVariables(p.vars);
    setTargetAudience(p.aud);
    setMethodologyType(p.type);
  };

  const handleGenerate = async (e?: React.FormEvent) => {
    if (e) e.preventDefault();
    if (!topic.trim()) return;

    setIsLoading(true);
    try {
      const res = await fetch("/api/ai/survey-generator", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          topic,
          variables,
          methodologyType,
          targetAudience,
          facultyCode: userProfile.facultyCode,
          locale
        })
      });

      const data = await res.json();
      if (!data.error) {
        setSurveyData(data);
      }
    } catch (err) {
      console.error("Survey generation error:", err);
    } finally {
      setIsLoading(false);
    }
  };

  // Convert survey data to clean Markdown for export / copy
  const generateMarkdownDocument = (data: SurveyQuestionnaireResult): string => {
    let md = `# ${data.title}\n\n`;
    md += `**Methodology Type:** ${data.methodologyType.toUpperCase()}\n`;
    md += `**Target Audience:** ${data.targetAudience}\n`;
    md += `**Generated By:** ResearchForge AI Academic Survey Architect\n\n`;
    md += `---\n\n`;

    // 1. Consent
    md += `## Section 1: Participant Informed Consent\n\n`;
    md += `**Study Title:** ${data.informedConsent.studyTitle}\n\n`;
    md += `**Investigator Info:** ${data.informedConsent.investigatorInfo}\n\n`;
    md += `### Purpose of the Study\n${data.informedConsent.purpose}\n\n`;
    md += `### Voluntary Participation & Withdrawal\n${data.informedConsent.voluntaryClause}\n\n`;
    md += `### Anonymity & Data Confidentiality\n${data.informedConsent.confidentiality}\n\n`;
    md += `### Data Protection & Storage\n${data.informedConsent.dataProtection}\n\n`;
    md += `**Contact for Ethical Inquiries:** ${data.informedConsent.contactInfo}\n\n`;
    md += `*Gateway Checkbox:* [ ] I have read the information above and voluntarily consent to participate in this study.\n\n`;
    md += `---\n\n`;

    // 2. Demographics
    md += `## Section 2: Demographic Screening\n\n`;
    data.demographics.forEach((d, i) => {
      md += `${i + 1}. **${d.question}**\n`;
      if (d.options && d.options.length > 0) {
        d.options.forEach((opt) => {
          md += `   - [ ] ${opt}\n`;
        });
      } else {
        md += `   - Short answer text: _______________________\n`;
      }
      md += `\n`;
    });
    md += `---\n\n`;

    // 3. Quantitative Constructs OR Qualitative Protocol
    if (data.methodologyType === "quantitative" && data.constructs) {
      md += `## Section 3: Empirical Survey Constructs (5-Point Likert Scale)\n\n`;
      md += `*Scale: 1 = Strongly Disagree | 2 = Disagree | 3 = Neutral / Undecided | 4 = Agree | 5 = Strongly Agree*\n\n`;

      data.constructs.forEach((c) => {
        md += `### ${c.constructName} (${c.variableCode})\n`;
        md += `*${c.description}*\n\n`;
        md += `| Item ID | Questionnaire Item Statement | Scale | Reverse Coded? |\n`;
        md += `|---|---|---|---|\n`;
        c.items.forEach((item) => {
          md += `| ${item.id} | ${item.itemText} | 1 - 2 - 3 - 4 - 5 | ${item.isReverseCoded ? "YES (Reverse Score in SPSS)" : "No"} |\n`;
        });
        md += `\n`;
      });
    } else if (data.interviewProtocol) {
      md += `## Section 3: Semi-Structured Qualitative Interview Protocol\n\n`;
      data.interviewProtocol.forEach((p, idx) => {
        md += `### Question ${idx + 1} • ${p.phase}\n`;
        md += `**Main Inquiry:** "${p.mainQuestion}"\n\n`;
        md += `**Probing Sub-Questions (Follow-up prompts):**\n`;
        p.probingQuestions.forEach((pr) => {
          md += `- *${pr}*\n`;
        });
        md += `\n**Interviewer Note:** ${p.interviewerNote}\n\n`;
      });
    }

    // 4. Ethics Checklist
    md += `---\n\n## Section 4: Institutional Review Board (IRB) Ethics Checklist\n\n`;
    data.ethicsChecklist.forEach((e) => {
      md += `- [x] **${e.title}** (${e.status.toUpperCase()}): ${e.requirement}\n`;
    });

    // 5. Google Forms Advice
    md += `\n---\n\n## Section 5: Google Forms & Data Collection Blueprint\n\n`;
    data.googleFormsTips.sections.forEach((s) => {
      md += `- **Structure:** ${s}\n`;
    });
    md += `\n### SPSS / Python Analysis Rules:\n`;
    data.googleFormsTips.spssEncodingRules.forEach((r) => {
      md += `- ${r}\n`;
    });

    return md;
  };

  const handleCopy = () => {
    if (!surveyData) return;
    const text = generateMarkdownDocument(surveyData);
    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  const handleDownloadMarkdown = () => {
    if (!surveyData) return;
    const text = generateMarkdownDocument(surveyData);
    const blob = new Blob([text], { type: "text/markdown;charset=utf-8;" });
    const url = URL.createObjectURL(blob);
    const link = document.createElement("a");
    link.href = url;
    link.download = `academic_survey_${surveyData.methodologyType}_${Date.now()}.md`;
    link.click();
    URL.revokeObjectURL(url);
  };

  const handlePrint = () => {
    window.print();
  };

  return (
    <div className="space-y-8 text-xs">
      {/* Generator Controls Card */}
      <div className="p-5 sm:p-6 rounded-3xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 shadow-sm space-y-5">
        <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-3 border-b border-slate-100 dark:border-slate-800 pb-4">
          <div>
            <div className="inline-flex items-center gap-1.5 px-2.5 py-0.5 rounded-full text-[10px] font-bold bg-indigo-50 dark:bg-indigo-950/60 text-indigo-600 dark:text-cyan-400 border border-indigo-200/60 dark:border-indigo-900/60 uppercase tracking-wider mb-1">
              <Sparkles className="w-3 h-3" />
              {locale === "bn" ? "এআই সার্ভে ও প্রশ্নমালা আর্কিটেক্ট" : "AI Survey & Instrument Architect"}
            </div>
            <h3 className="text-base sm:text-lg font-bold text-slate-900 dark:text-white">
              {locale === "bn" ? "নিরপেক্ষ ও প্রাতিষ্ঠানিক মানসম্পন্ন প্রশ্নমালা জেনারেটর" : "Generate Rigorous Bias-Free Academic Instruments"}
            </h3>
          </div>

          {/* Quick Presets */}
          <div className="flex items-center gap-1.5 flex-wrap">
            <span className="text-[10px] font-bold text-slate-400 mr-1">{locale === "bn" ? "নমুনা প্রিসেট:" : "Presets:"}</span>
            {presets.map((p, idx) => (
              <button
                key={idx}
                type="button"
                onClick={() => applyPreset(p)}
                className="px-2.5 py-1 rounded-lg bg-slate-100 dark:bg-slate-800 hover:bg-indigo-50 dark:hover:bg-indigo-950 text-slate-700 dark:text-slate-300 text-[10px] font-semibold transition"
              >
                {p.label}
              </button>
            ))}
          </div>
        </div>

        <form onSubmit={handleGenerate} className="space-y-4">
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
            {/* Research Topic */}
            <div className="sm:col-span-2">
              <label className="block font-semibold text-slate-700 dark:text-slate-300 mb-1">
                {locale === "bn" ? "থিসিস বা গবেষণার শিরোনাম / টপিক:" : "Thesis Title or Research Topic:"}
              </label>
              <input
                type="text"
                value={topic}
                onChange={(e) => setTopic(e.target.value)}
                placeholder="e.g. Factors influencing cloud migration security in financial institutions..."
                className="w-full px-3.5 py-2.5 rounded-xl border border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-800 text-slate-900 dark:text-white text-xs focus:outline-none focus:ring-2 focus:ring-indigo-500 font-medium"
              />
            </div>

            {/* Target Variables */}
            <div>
              <label className="block font-semibold text-slate-700 dark:text-slate-300 mb-1">
                {locale === "bn" ? "পরিমাপযোগ্য চলকসমূহ (Constructs / Variables):" : "Target Variables / Constructs to Measure:"}
              </label>
              <input
                type="text"
                value={variables}
                onChange={(e) => setVariables(e.target.value)}
                placeholder="e.g. Perceived Usefulness, User Trust, Institutional Resistance..."
                className="w-full px-3.5 py-2 rounded-xl border border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-800 text-slate-900 dark:text-white text-xs focus:outline-none focus:ring-2 focus:ring-indigo-500 font-medium"
              />
            </div>

            {/* Target Audience */}
            <div>
              <label className="block font-semibold text-slate-700 dark:text-slate-300 mb-1">
                {locale === "bn" ? "টার্গেট অংশগ্রহণকারী (Target Audience):" : "Target Respondents / Informants:"}
              </label>
              <input
                type="text"
                value={targetAudience}
                onChange={(e) => setTargetAudience(e.target.value)}
                placeholder="e.g. Software Engineers, Final-Year Students, Micro-merchants..."
                className="w-full px-3.5 py-2 rounded-xl border border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-800 text-slate-900 dark:text-white text-xs focus:outline-none focus:ring-2 focus:ring-indigo-500 font-medium"
              />
            </div>
          </div>

          {/* Methodology Toggle Buttons */}
          <div className="pt-2 flex flex-col sm:flex-row sm:items-center justify-between gap-4">
            <div className="flex items-center gap-2">
              <span className="font-bold text-slate-700 dark:text-slate-300 text-xs">{locale === "bn" ? "ইনস্ট্রুমেন্ট মোড:" : "Mode:"}</span>
              <div className="p-1 rounded-xl bg-slate-100 dark:bg-slate-800 flex items-center gap-1 border border-slate-200 dark:border-slate-700">
                <button
                  type="button"
                  onClick={() => setMethodologyType("quantitative")}
                  className={`px-3 py-1.5 rounded-lg text-xs font-bold transition flex items-center gap-1.5 ${
                    methodologyType === "quantitative"
                      ? "bg-indigo-600 text-white shadow-sm"
                      : "text-slate-600 dark:text-slate-300 hover:text-slate-900"
                  }`}
                >
                  <ListOrdered className="w-3.5 h-3.5" />
                  <span>{locale === "bn" ? "১০-আইটেম লিকার্ট স্কেল (Quant)" : "10-Item Likert Scale (Quant)"}</span>
                </button>
                <button
                  type="button"
                  onClick={() => setMethodologyType("qualitative")}
                  className={`px-3 py-1.5 rounded-lg text-xs font-bold transition flex items-center gap-1.5 ${
                    methodologyType === "qualitative"
                      ? "bg-emerald-600 text-white shadow-sm"
                      : "text-slate-600 dark:text-slate-300 hover:text-slate-900"
                  }`}
                >
                  <Users className="w-3.5 h-3.5" />
                  <span>{locale === "bn" ? "৬-ধাপের ইন্টারভিউ প্রোটোকল (Qual)" : "6-Phase Interview Protocol (Qual)"}</span>
                </button>
              </div>
            </div>

            <button
              type="submit"
              disabled={isLoading}
              className="px-6 py-2.5 rounded-xl bg-gradient-to-r from-indigo-600 via-blue-600 to-cyan-500 hover:from-indigo-700 hover:to-cyan-600 text-white font-bold text-xs shadow-md shadow-indigo-500/20 flex items-center justify-center gap-2 transition"
            >
              {isLoading ? (
                <>
                  <Loader2 className="w-4 h-4 animate-spin" />
                  <span>{locale === "bn" ? "এআই সাইকোমেট্রিক ইঞ্জিন প্রস্তুত করছে..." : "Synthesizing Instrument..."}</span>
                </>
              ) : (
                <>
                  <Sparkles className="w-4 h-4" />
                  <span>{locale === "bn" ? "সম্পূর্ণ প্রশ্নমালা ও সম্মতিপত্র তৈরি করুন" : "Generate Complete Instrument"}</span>
                </>
              )}
            </button>
          </div>
        </form>
      </div>

      {/* Generated Survey Display */}
      {surveyData && (
        <div className="space-y-6 animate-in fade-in duration-300">
          {/* Action Export Bar */}
          <div className="p-4 rounded-2xl bg-slate-900 text-white flex flex-wrap items-center justify-between gap-3 shadow-md">
            <div>
              <span className="text-[10px] font-bold uppercase tracking-wider text-cyan-400 block">
                {locale === "bn" ? "প্রস্তুতকৃত অ্যাকাডেমিক ইনস্ট্রুমেন্ট" : "Generated Academic Instrument"}
              </span>
              <h4 className="font-bold text-sm text-white">{surveyData.title}</h4>
            </div>

            <div className="flex items-center gap-2">
              <button
                onClick={handleCopy}
                className="px-3 py-1.5 rounded-xl bg-white/10 hover:bg-white/20 text-white font-semibold flex items-center gap-1.5 transition text-xs"
              >
                {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
                <span>{copied ? (locale === "bn" ? "কপি সম্পন্ন!" : "Copied!") : (locale === "bn" ? "কপি টেক্সট" : "Copy Text")}</span>
              </button>

              <button
                onClick={handleDownloadMarkdown}
                className="px-3 py-1.5 rounded-xl bg-indigo-600 hover:bg-indigo-700 text-white font-semibold flex items-center gap-1.5 transition text-xs"
              >
                <Download className="w-3.5 h-3.5" />
                <span>{locale === "bn" ? "Markdown (.md) ডাউনলোড" : "Export Markdown (.md)"}</span>
              </button>

              <button
                onClick={handlePrint}
                className="px-3 py-1.5 rounded-xl bg-slate-800 hover:bg-slate-700 text-white font-semibold flex items-center gap-1.5 transition text-xs"
              >
                <Printer className="w-3.5 h-3.5" />
                <span>{locale === "bn" ? "প্রিন্ট / PDF" : "Print / PDF"}</span>
              </button>
            </div>
          </div>

          {/* Section 1: Informed Consent Form */}
          <div className="p-6 rounded-3xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 shadow-sm space-y-4">
            <div className="flex items-center gap-2 border-b border-slate-100 dark:border-slate-800 pb-3">
              <ShieldCheck className="w-5 h-5 text-emerald-600 dark:text-emerald-400" />
              <div>
                <span className="text-[10px] font-bold text-emerald-600 dark:text-emerald-400 uppercase tracking-wider block">
                  Section 1 • Institutional Ethics & Compliance
                </span>
                <h4 className="text-sm sm:text-base font-bold text-slate-900 dark:text-white">
                  {surveyData.informedConsent.title}
                </h4>
              </div>
            </div>

            <div className="p-4 rounded-2xl bg-slate-50 dark:bg-slate-800/50 border border-slate-200/60 dark:border-slate-700/60 space-y-3 leading-relaxed text-slate-700 dark:text-slate-300 text-xs">
              <p>
                <strong>{locale === "bn" ? "গবেষণার বিষয়:" : "Research Title:"}</strong> {surveyData.informedConsent.studyTitle}
              </p>
              <p>
                <strong>{locale === "bn" ? "তত্ত্বাবধানকারী:" : "Investigator Role:"}</strong> {surveyData.informedConsent.investigatorInfo}
              </p>
              <p>
                <strong>{locale === "bn" ? "গবেষণার উদ্দেশ্য:" : "Objective:"}</strong> {surveyData.informedConsent.purpose}
              </p>
              <p>
                <strong>{locale === "bn" ? "স্বেচ্ছাসেবী নীতি ও প্রত্যাহার অধিকার:" : "Voluntary Terms:"}</strong> {surveyData.informedConsent.voluntaryClause}
              </p>
              <p>
                <strong>{locale === "bn" ? "গোপনীয়তা ও অ্যানোনিমিটি:" : "Confidentiality:"}</strong> {surveyData.informedConsent.confidentiality}
              </p>
              <p>
                <strong>{locale === "bn" ? "যোগাযোগ:" : "Ethical Contact:"}</strong> {surveyData.informedConsent.contactInfo}
              </p>

              <div className="pt-2 border-t border-slate-200 dark:border-slate-700 flex items-center gap-2 font-bold text-indigo-700 dark:text-cyan-300">
                <input type="checkbox" checked readOnly className="w-4 h-4 rounded text-indigo-600" />
                <span>
                  {locale === "bn"
                    ? "আমি সম্মতিপত্রের সকল শর্তাবলি পড়েছি এবং স্বেচ্ছায় এই গবেষণামূলক জরিপে অংশগ্রহণ করতে সম্মতি দিচ্ছি।"
                    : "I have read the informed consent statement and voluntarily agree to participate in this study."}
                </span>
              </div>
            </div>
          </div>

          {/* Section 2: Demographic Screening */}
          <div className="p-6 rounded-3xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 shadow-sm space-y-4">
            <div className="flex items-center gap-2 border-b border-slate-100 dark:border-slate-800 pb-3">
              <Users className="w-5 h-5 text-indigo-600 dark:text-cyan-400" />
              <div>
                <span className="text-[10px] font-bold text-indigo-600 dark:text-cyan-400 uppercase tracking-wider block">
                  Section 2 • Respondent Profiling
                </span>
                <h4 className="text-sm sm:text-base font-bold text-slate-900 dark:text-white">
                  {locale === "bn" ? "জনতাত্ত্বিক ও প্রাথমিক তথ্য (Demographics)" : "Demographic Screening Questions"}
                </h4>
              </div>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              {surveyData.demographics.map((demo, idx) => (
                <div key={demo.id} className="p-4 rounded-2xl bg-slate-50 dark:bg-slate-800/40 border border-slate-200/60 dark:border-slate-800 space-y-2">
                  <span className="font-bold text-slate-900 dark:text-white block text-xs">
                    {idx + 1}. {demo.question}
                  </span>
                  {demo.options ? (
                    <div className="space-y-1.5 pl-1">
                      {demo.options.map((opt, oIdx) => (
                        <div key={oIdx} className="flex items-center gap-2 text-slate-600 dark:text-slate-300 text-[11px]">
                          <span className="w-3 h-3 rounded-full border border-slate-300 dark:border-slate-600" />
                          <span>{opt}</span>
                        </div>
                      ))}
                    </div>
                  ) : (
                    <div className="h-8 rounded-lg border border-dashed border-slate-300 dark:border-slate-700 bg-white dark:bg-slate-900 flex items-center px-3 text-[11px] text-slate-400">
                      Short text response...
                    </div>
                  )}
                </div>
              ))}
            </div>
          </div>

          {/* Section 3: Likert Items (Quantitative) OR Interview Protocol (Qualitative) */}
          {surveyData.methodologyType === "quantitative" && surveyData.constructs && (
            <div className="p-6 rounded-3xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 shadow-sm space-y-6">
              <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2 border-b border-slate-100 dark:border-slate-800 pb-3">
                <div className="flex items-center gap-2">
                  <ListOrdered className="w-5 h-5 text-indigo-600 dark:text-cyan-400" />
                  <div>
                    <span className="text-[10px] font-bold text-indigo-600 dark:text-cyan-400 uppercase tracking-wider inline-flex items-center">
                      <span>Section 3 • Empirical Measurement Matrix (10 Items)</span>
                      <AcademicTooltip term="cronbach" />
                    </span>
                    <h4 className="text-sm sm:text-base font-bold text-slate-900 dark:text-white inline-flex items-center">
                      <span>{locale === "bn" ? "৫-পয়েন্ট লিকার্ট স্কেল প্রশ্নমালা" : "5-Point Likert Scale Survey Items"}</span>
                      <AcademicTooltip term="likert" />
                    </h4>
                  </div>
                </div>

                <div className="flex items-center gap-1 text-[10px] font-bold text-slate-500 bg-slate-100 dark:bg-slate-800 px-3 py-1 rounded-full">
                  <span>1=SD</span> • <span>2=D</span> • <span>3=N</span> • <span>4=A</span> • <span>5=SA</span>
                </div>
              </div>

              {surveyData.constructs.map((construct, cIdx) => (
                <div key={cIdx} className="space-y-3">
                  <div className="p-3 rounded-xl bg-indigo-50/70 dark:bg-indigo-950/40 border border-indigo-100 dark:border-indigo-900/60 flex items-center justify-between">
                    <div>
                      <h5 className="font-bold text-xs text-indigo-950 dark:text-cyan-300">
                        {construct.constructName}
                      </h5>
                      <p className="text-[11px] text-slate-600 dark:text-slate-400">
                        {construct.description}
                      </p>
                    </div>
                    <span className="px-2 py-0.5 rounded bg-indigo-200 dark:bg-indigo-900 text-indigo-800 dark:text-cyan-300 font-mono text-[10px] font-bold shrink-0">
                      {construct.variableCode}
                    </span>
                  </div>

                  <div className="space-y-2">
                    {construct.items.map((item, iIdx) => (
                      <div
                        key={item.id}
                        className={`p-4 rounded-2xl border transition-all flex flex-col sm:flex-row sm:items-center justify-between gap-3 ${
                          item.isReverseCoded
                            ? "bg-amber-50/50 dark:bg-amber-950/20 border-amber-200 dark:border-amber-900/60"
                            : "bg-slate-50 dark:bg-slate-800/40 border-slate-200/60 dark:border-slate-800"
                        }`}
                      >
                        <div className="space-y-1 flex-1">
                          <div className="flex items-center gap-2">
                            <span className="font-bold text-slate-900 dark:text-white text-xs">
                              {item.id.toUpperCase()}:
                            </span>
                            {item.isReverseCoded && (
                              <span className="px-2 py-0.5 rounded-full text-[9px] font-bold bg-amber-200 dark:bg-amber-900/70 text-amber-900 dark:text-amber-300 border border-amber-300 dark:border-amber-800">
                                {locale === "bn" ? "রিভার্স কোডেড (Reverse-Coded Item)" : "Reverse-Coded Item"}
                              </span>
                            )}
                          </div>
                          <p className="text-slate-800 dark:text-slate-200 text-xs font-medium leading-relaxed">
                            {item.itemText}
                          </p>
                          <span className="text-[10px] text-slate-400 block">
                            Rationale: {item.rationale}
                          </span>
                        </div>

                        {/* Visual 5-Point Radio Simulator */}
                        <div className="flex items-center gap-2 sm:gap-3 bg-white dark:bg-slate-900 p-2 rounded-xl border border-slate-200 dark:border-slate-700 shrink-0 self-start sm:self-auto">
                          {[1, 2, 3, 4, 5].map((val) => (
                            <div key={val} className="flex flex-col items-center gap-1 text-[10px]">
                              <span className="font-semibold text-slate-400">{val}</span>
                              <div className="w-4 h-4 rounded-full border border-slate-300 dark:border-slate-600 hover:border-indigo-600" />
                            </div>
                          ))}
                        </div>
                      </div>
                    ))}
                  </div>
                </div>
              ))}
            </div>
          )}

          {/* Section 3 (Qualitative Protocol): Semi-Structured Interview */}
          {surveyData.methodologyType === "qualitative" && surveyData.interviewProtocol && (
            <div className="p-6 rounded-3xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 shadow-sm space-y-6">
              <div className="flex items-center gap-2 border-b border-slate-100 dark:border-slate-800 pb-3">
                <BookOpen className="w-5 h-5 text-emerald-600 dark:text-emerald-400" />
                <div>
                  <span className="text-[10px] font-bold text-emerald-600 dark:text-emerald-400 uppercase tracking-wider block">
                    Section 3 • Semi-Structured Interview Protocol (6 Phases)
                  </span>
                  <h4 className="text-sm sm:text-base font-bold text-slate-900 dark:text-white">
                    {locale === "bn" ? "গুণগত সাক্ষাৎকার প্রোটোকল ও ফলো-আপ প্রশ্নমালা" : "Qualitative Interview Protocol with Probing Questions"}
                  </h4>
                </div>
              </div>

              <div className="space-y-4">
                {surveyData.interviewProtocol.map((proto, idx) => (
                  <div key={proto.id} className="p-5 rounded-2xl bg-slate-50 dark:bg-slate-800/40 border border-slate-200/60 dark:border-slate-800 space-y-3">
                    <div className="flex items-center justify-between">
                      <span className="px-2.5 py-0.5 rounded-full text-[10px] font-bold bg-emerald-100 dark:bg-emerald-950 text-emerald-800 dark:text-emerald-300">
                        {proto.phase}
                      </span>
                      <span className="text-[10px] font-mono text-slate-400">Q{idx + 1}</span>
                    </div>

                    <h5 className="text-xs sm:text-sm font-bold text-slate-900 dark:text-white leading-snug">
                      "{proto.mainQuestion}"
                    </h5>

                    <div className="p-3 rounded-xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-700/80 space-y-1.5">
                      <span className="text-[10px] font-bold text-indigo-600 dark:text-cyan-400 uppercase tracking-wider block">
                        {locale === "bn" ? "প্রোবিং বা ফলো-আপ প্রশ্ন (Probing Sub-Questions):" : "Probing Sub-Questions:"}
                      </span>
                      <ul className="space-y-1 pl-4 list-disc text-slate-600 dark:text-slate-300 text-[11px]">
                        {proto.probingQuestions.map((pr, pIdx) => (
                          <li key={pIdx}>{pr}</li>
                        ))}
                      </ul>
                    </div>

                    <div className="text-[10px] text-slate-500 italic">
                      <strong>Interviewer Note:</strong> {proto.interviewerNote}
                    </div>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Section 4: Ethics & Compliance Checklist */}
          <div className="p-6 rounded-3xl bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 shadow-sm space-y-4">
            <div className="flex items-center gap-2 border-b border-slate-100 dark:border-slate-800 pb-3">
              <ShieldCheck className="w-5 h-5 text-cyan-600 dark:text-cyan-400" />
              <div>
                <span className="text-[10px] font-bold text-cyan-600 dark:text-cyan-400 uppercase tracking-wider block">
                  Section 4 • IRB Research Ethics Audit
                </span>
                <h4 className="text-sm sm:text-base font-bold text-slate-900 dark:text-white">
                  {locale === "bn" ? "ইনস্টিটিউশনাল এথিক্স ও ডাটা প্রটেকশন চেকলিস্ট" : "Institutional Ethics & Data Security Checklist"}
                </h4>
              </div>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
              {surveyData.ethicsChecklist.map((eth, idx) => (
                <div key={idx} className="p-3.5 rounded-2xl bg-slate-50 dark:bg-slate-800/40 border border-slate-200/60 dark:border-slate-800 flex items-start gap-2.5">
                  <Check className="w-4 h-4 text-emerald-500 shrink-0 mt-0.5" />
                  <div>
                    <span className="font-bold text-xs text-slate-900 dark:text-white block">
                      {eth.title}
                    </span>
                    <span className="text-[11px] text-slate-500 dark:text-slate-400 leading-relaxed block mt-0.5">
                      {eth.requirement}
                    </span>
                  </div>
                </div>
              ))}
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
